import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@/context/index";



export const metadata: Metadata = {
  title: "PowerCycle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
      <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
